AWSTemplateFormatVersion: '2010-09-09'
Description: 'Construction Site AI Agent Infrastructure'

Resources:
  AIAgentLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: construction-ai-agent
      Runtime: nodejs18.x
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return { statusCode: 200, body: JSON.stringify('Hello') };
          };
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'

  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: construction-ai-api
      EndpointConfiguration:
        Types:
          - REGIONAL

  AIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGateway
      ParentId: !GetAtt APIGateway.RootResourceId
      PathPart: ai

  AIMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref APIGateway
      ResourceId: !Ref AIResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AIAgentLambda.Arn}/invocations'

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AIAgentLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub '${APIGateway}/*/*'

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: AIMethod
    Properties:
      RestApiId: !Ref APIGateway
      StageName: prod

Outputs:
  APIEndpoint:
    Value: !Sub 'https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'